subdir-ccflags-y += -Werror

ccflags-y += -I$(srctree)/drivers/media/platform/tegra
ccflags-y += -I$(srctree)/drivers/video/tegra/camera

#obj-$(CONFIG_SL_VIDEO_ZEDONE4K) += max929x.o
obj-$(CONFIG_SL_VIDEO_ZEDONE4K) += sl_zedxone_uhd.o
