subdir-ccflags-y += -Werror

ccflags-y += -I$(srctree)/drivers/media/platform/tegra
ccflags-y += -I$(srctree)/drivers/media/
ccflags-y += -I$(srctree)/drivers/video/tegra/camera

obj-$(CONFIG_SL_VIDEO_ZEDXPRO) += sl_zedxpro.o
