#!/bin/bash

# set -x

pushd /boot/extlinux &> /dev/null
sync
EXTLINUX=$(ls extlinux.conf)

if [ -n "${EXTLINUX}" ]; then

	if [ ! -e ${EXTLINUX}.sl-backup ]; then

		cp ${EXTLINUX} ${EXTLINUX}.sl-backup

		sync

	fi

	if [ ! -f "/etc/nv_tegra_release" ]; then
		echo "File not found: /etc/nv_tegra_release"
		exit 1
	fi

	l4t_version=$(grep -oP 'R\K[0-9]+' "/etc/nv_tegra_release" | head -1)
	l4t_minor=$(grep -oP ': \K[0-9]+' "/etc/nv_tegra_release" | head -1)
	l4t_rev=$(grep -oP ': \K[0-9].\K[0-9]' "/etc/nv_tegra_release" | head -1)


	## Get current DTB in /boot/dtb/
	board=$(ls /boot/dtb/kernel_* | awk -F"." '{print $1}' | awk -F"_" '{print $NF}' | awk -F"-" '{print $2}')
	teg_version=$(ls /boot/dtb/kernel_* | awk -F"." '{print $1}' | awk -F"_" '{print $NF}' | awk -F"-" '{print $1}')
	if [ -z "$board" ] ## fallback to /boot/kernel_*
	then
		board=$(ls /boot/kernel_* | awk -F"." '{print $1}' | awk -F"_" '{print $NF}' | awk -F"-" '{print $2}')
		teg_version=$(ls /boot/kernel_* | awk -F"." '{print $1}' | awk -F"_" '{print $NF}' | awk -F"-" '{print $1}')
	fi
	extension=$teg_version-$board
	echo "Detected DTB to update : $extension"
	value=$(</boot/stereolabs/utils/zlconfig)
	echo "Detected capture card : $value"
	sudo python3 /boot/stereolabs/utils/extlinux.py $value
	RC=$?


	if (( $RC != 0 )); then
		echo "[Error] Fail to update extlinux.conf. This Will require a custom configuration."
		sudo cp "${EXTLINUX}.sl-backup" ${EXTLINUX}
	fi


	sync

	popd &> /dev/null
fi

## Update isp config
sudo chmod 664 /var/nvidia/nvcam/settings/zedx_ar0234.isp
sudo chown root:root /var/nvidia/nvcam/settings/zedx_ar0234.isp

## Udpate Daemon and argus
## modify argus daemon to avoid timeout when using multiple cameras
sudo sed -i '/^\[Service\]$/ a Environment="enableCamInfiniteTimeout=1"' /etc/systemd/system/nvargus-daemon.service

if [[ $l4t_version -eq 36 && $l4t_minor -eq 4 ]]; then
	cp /usr/lib/aarch64-linux-gnu/tegra/libnvisppg.so /usr/lib/aarch64-linux-gnu/tegra/libnvisppg.so.sl-backup
	if [ $l4t_rev -eq 3 ]; then 
		mv /tmp/R36.4.3/libnvisppg.so /usr/lib/aarch64-linux-gnu/tegra/libnvisppg.so
	elif [ $l4t_rev -eq 0 ]; then 
		mv /tmp/R36.4.0/libnvisppg.so /usr/lib/aarch64-linux-gnu/tegra/libnvisppg.so
	else
		echo "Failed to patch nvargus : Please update your system with : 'sudo apt update && sudo apt upgrade'"
	fi
fi

## Move service from /tmp/ to /etc/systemd/system
mv /tmp/zed_x_daemon.service /etc/systemd/system/zed_x_daemon.service
## enable service
sudo systemctl enable zed_x_daemon.service

sync

exit 0

