obj-$(CONFIG_SL_SER_MAX9295) += max9295/

# The driver of the dual deserializer.
obj-$(CONFIG_SL_DESER_MAX9296) += max9296/

# The driver of the quad deserializer.
obj-$(CONFIG_SL_DESER_MAX96712) += max96712/

obj-$(CONFIG_SL_DESER_MAX96724) += max96724/

# The driver of the ZED-X camera.
obj-$(CONFIG_SL_VIDEO_ZEDX) += zedx/

# The driver of the ZED-X camera.
obj-$(CONFIG_SL_VIDEO_ZEDONE4K) += zedone4k/

obj-$(CONFIG_SL_VIDEO_ZEDXPRO) += zedxpro/

# Just if necessary
# ccflags-y += -I$(src)/../../include
